steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/cs436-minitasks/minitasks-repo/minitasks-api:v1', '.']
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/cs436-minitasks/minitasks-repo/minitasks-api:v1']
# Store images in Artifact Registry
images:
  - 'us-central1-docker.pkg.dev/cs436-minitasks/minitasks-repo/minitasks-api:v1' 