apiVersion: apps/v1
kind: Deployment
metadata:
  name: minitasks-api
  labels:
    app: minitasks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minitasks
  template:
    metadata:
      labels:
        app: minitasks
    spec:
      containers:
      - name: api
        image: us-central1-docker.pkg.dev/cs436-minitasks/minitasks-repo/minitasks-api:v1
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        env:
        - name: DB_PATH
          value: "/app/data/minitasks.db"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: db-storage
          mountPath: /app/data
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: minitasks-db-pvc 